// GENERATED by scripts/generate-prices.mjs — do not edit by hand.
// Source of truth: pricing.config.mjs
window.PRICING = {
  "rates": {
    "child": 45,
    "parent": 55
  },
  "packs": {
    "decouverte": {
      "label": "Découverte",
      "childSessions": 10,
      "parentSessions": 2,
      "discountPct": 6,
      "value": 560,
      "price": 525,
      "valueText": "560€",
      "priceText": "525€"
    },
    "approfondissement": {
      "label": "Approfondissement",
      "childSessions": 20,
      "parentSessions": 4,
      "discountPct": 7,
      "value": 1120,
      "price": 1040,
      "valueText": "1 120€",
      "priceText": "1 040€"
    },
    "consolidation": {
      "label": "Consolidation",
      "childSessions": 40,
      "parentSessions": 6,
      "discountPct": 8.5,
      "value": 2130,
      "price": 1950,
      "valueText": "2 130€",
      "priceText": "1 950€"
    },
    "equilibre": {
      "label": "Équilibre",
      "childSessions": 80,
      "parentSessions": 8,
      "discountPct": 12,
      "value": 4040,
      "price": 3555,
      "valueText": "4 040€",
      "priceText": "3 555€",
      "perWeekText": "90€",
      "perMonthText": "355€"
    }
  },
  "minPriceText": "525€",
  "maxPriceText": "3 555€"
};
