// scripts/render.mjs

/** Format an integer with French thousands separators (regular space). 1040 -> "1 040". */
export function formatNumberFr(n) {
  return String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}

/** Euro string. `space: true` -> "525 €" (cards); `space: false` -> "525€" (table/chatbot). */
export function euro(n, { space = true } = {}) {
  return `${formatNumberFr(n)}${space ? " " : ""}€`;
}

/** Build the generated browser data file content (window.PRICING). */
export function renderDataFile(computed, rates) {
  const packs = {};
  for (const p of computed) {
    packs[p.id] = {
      label: p.label,
      childSessions: p.childSessions,
      parentSessions: p.parentSessions,
      discountPct: p.discountPct,
      value: p.value,
      price: p.price,
      valueText: euro(p.value, { space: false }),
      priceText: euro(p.price, { space: false }),
      ...(p.perWeek != null
        ? {
            perWeekText: euro(p.perWeek, { space: false }),
            perMonthText: euro(p.perMonth, { space: false }),
          }
        : {}),
    };
  }
  const prices = computed.map((p) => p.price);
  const data = {
    rates,
    packs,
    minPriceText: euro(Math.min(...prices), { space: false }),
    maxPriceText: euro(Math.max(...prices), { space: false }),
  };
  return (
    "// GENERATED by scripts/generate-prices.mjs — do not edit by hand.\n" +
    "// Source of truth: pricing.config.mjs\n" +
    `window.PRICING = ${JSON.stringify(data, null, 2)};\n`
  );
}

/** Replace content between <!--price:KEY--> … <!--/price--> for each key. */
export function injectMarkers(html, replacements) {
  let out = html;
  const missing = [];
  for (const [key, value] of Object.entries(replacements)) {
    const safeKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`(<!--price:${safeKey}-->)[\\s\\S]*?(<!--/price-->)`);
    if (!re.test(out)) {
      missing.push(key);
      continue;
    }
    out = out.replace(re, `$1${value}$2`);
  }
  return { html: out, missing };
}
